### ISSUE TITLE
How to implement extend functionality?

### ISSUE THREAD

**Issue by zmitry** [neuledge/computed-types#116]
I need to implement extend feature like in zod. 
I want to modify user to accept name as number instead of string. 
```
schema.extend(user, {
name: number
})
```

**Comment by moshest** [comment]
This is not a valid TypeScript interface. You can't extend property and change it's type. I would recommend to create an abstract user without a name and then extend it with `name: string` and `name: number` instead.

**Comment by zmitry** [comment]
@moshest It's literaly same for typescript Merge<BaseUser, { name: number /* customization */ }>; 
What I have right now that I'm not in control of base schema. I get generated schema and in some cases I want to override some properties and make them more strict or relaxed. It is implemented in https://github.com/colinhacks/zod#extend. 
I solved it with adding extra field to user schema called .shape and then I can do regular spread but it would be good to have that built in maybe.

**Comment by moshest** [comment]
You can always add more validation on a type, as long the type remain the same. You can't switch suddenly a number to a string and expect it to work.

I would recommend using [`Schema.either()`](https://github.com/neuledge/computed-types#schemaeither) or [`.construct()`](https://github.com/neuledge/computed-types#construct).
