### ISSUE TITLE
Comments gets lost when I extend it with Type

### ISSUE THREAD

**Issue by chwon-ezstrading** [neuledge/computed-types#152]
```
export const DelLogReqQuerySchema = Schema({
    /** delete id, or delete all logs.*/
    id: string.optional(),
})
export interface IDelLogReqQuery extends Type<typeof DelLogReqQuerySchema> {}
```

I use automation to create swagger doc.
Let's say I use IDelLogReqQuery interface for documentation.
Before minor version 11, I can see comments for `id` prop but that is no longer the case after minor version 11.

I used https://github.com/YousefED/typescript-json-schema to read the type.

**Comment by moshest** [comment]
I believe this related to this change: https://github.com/neuledge/computed-types/commit/23fdc7dbaf6afe6a50130d4159dafb67dd6ab1a9

Can you confirm the problem solved if you remove the `.optional()` option?

**Comment by chwon-ezstrading** [comment]
but I need to use optional to validate query params

**Comment by moshest** [comment]
I'm not sure it's something I can address right now. I need to know what's the requirement of that lib so we can pass through the comments.

Please open an issue on https://github.com/YousefED/typescript-json-schema lib and ask for some guidance. I'm closing this until we know how we can address it.
