### ISSUE TITLE
Validating nested objects

### ISSUE THREAD

**Issue by wereHamster** [neuledge/computed-types#164]
I'm having issues validating nested objects. There are no examples how to do it. I tried the following two approaches:

```js
const validator = Schema({
  foo: {
    bar: string.min(1)
  }
})

validator({ foo: { bar: "" } }) // <- error path is ["foo", "foo", "bar"]
```

```js
const validator = Schema({
  foo: Schema({
    bar: string.min(1)
  })
})

validator({ foo: { bar: "" } }) // <- error path is ["foo", "bar"]
```

The first case looks like a bug.

**Comment by moshest** [comment]
Hi @wereHamster, thank you for reporting!

I released `v1.11.2` that should solve this issue.

**Comment by wereHamster** [comment]
From the tests in the commit I assume both forms are supported? Can you confirm?

**Comment by moshest** [comment]
Yes, both ways are supported.
