### ISSUE TITLE
Validating optional fields are defined

### ISSUE THREAD

**Issue by BryceCicada** [neuledge/computed-types#166]
I'm enjoying this library.  However, I'm struggling with the following...

If I have a type with an optional field, and an instance of that type for which I want to validate the optional field is populated, I'm doing like: 
```
      type MyType = { foo?: string }  // optional field foo
      const myObject: MyType = {foo: "bar"}  // foo is populated, so I want this to validate

      const schema = Schema({
        foo: string
      })

      const validator = schema.destruct()

      const [ err, validatedObject ] = validator(myObject)
```
However, this gives an error on applying `validator(myObject)`:
```
Argument of type 'MyType' is not assignable to parameter of type '{ foo: string; }'.
  Types of property 'foo' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.ts(2345)
```

I also tried using `unknown` like:
```
      const schema = Schema({
        foo: unknown.string()
      })
```
hoping that this might be more tolerant to the input type being undefined, but it's the same error.

Is there a way to do this?

**Comment by BryceCicada** [comment]
So I was doing some more thinking about this.  

I think the challenge can be explained by an example: a variable of type `{ foo?: string }` is assignable by objects without property `foo`, eg `const a: { foo?: string } = {}` is fine.  This example shows that I'm not looking to only validate the properties that exist but also expecting to validate the existence of a property. I can imagine this is more like some misaligned expectation on my part.  

One reason I'm enjoying this library is that I can do validation + type narrowing in a single step.  I'm still tempted to understand an 'elegant' way of achieving this validation.

**Comment by BryceCicada** [comment]
So, the example above has clarified this for me.  The task is to populate the optional fields on the type with `undefined`, and then validate the fields as normal.  

Using a conditional type `Complete` as described [here](https://medium.com/terria/typescript-transforming-optional-properties-to-required-properties-that-may-be-undefined-7482cb4e1585), I can define a function `complete(x: T): Complete<T>` that populates the missing types with `undefined`.

```
      type MyType = { foo?: string }

      type Complete<T> = {
        [P in keyof Required<T>]: Pick<T, P> extends Required<Pick<T, P>> ? T[P] : (T[P] | undefined);
      }

      // A function to ensure all the optional properties are populated with undefined
      const complete = (x: MyType): Complete<MyType> => ({...{foo: undefined}, ...x})

      // Now validate as normal against an 'unknown.string()'.
      // Forgive the unnecessary type declaration here... just being explicit.
      const myObject: Complete<MyType> = complete({ foo: "bar" })

      const schema = Schema({
        foo: unknown.string()
      })

      const validator = schema.destruct()

      const [err, validatedJsonGraph] = validator(myObject)
```

I'm going close this issue, since I've explored it and understood it to my satisfaction.

**Comment by moshest** [comment]
Hi Chris, and thank you for all the inputs and suggested solution.

I think the current behavior is expected. As you said, once you define a property, the validator enforce you to provide it, unless you mark it as `optional` (or `strictOptional`).

I can suggest 2 additional solutions for this problem:

1. Use `.construct` to redefine the property input:
```ts
unknown.string().construct((val?: unknown) => val);
```
2. Use `Type` to override the input type: 
```ts
const [ err, validatedObject ] = validator(myObject as Type<typeof schema>);
```

I hope it helps.

**Comment by BryceCicada** [comment]
This is great.

The solution `unknown.string().construct((val?: unknown) => [val])` works well.

Thank you.
