### ISSUE TITLE
Functionality when one input equals another

### ISSUE THREAD

**Issue by TolyaDeveloper** [neuledge/computed-types#202]
I'm having a Schema with fields: **email**, **password** and **repeat_password**
Is there out of the box functionality where it checks if **repeat_password** is the same as the **password**? I can't find it for now

**Comment by moshest** [comment]
You can do is via the [validators chain](https://github.com/neuledge/computed-types#validators-chain) on the schema object:

```ts
import * as EmailValidator from 'email-validator';
import zxcvbn from 'zxcvbn';

Schema({
  email: unknown.string().trim().test(EmailValidator.validate, 'Invalid email address'),
  password: unknown.string().trim().between(6, 100).test((value) => zxcvbn(value) > 0, 'Weak password'),
  repeatPassword: unknown.string().trim().between(6, 100),
})
  .test((value) => value.password === value. repeatPassword, 'Passwords do not match');
```
