### ISSUE TITLE
Uncaught SyntaxError: The requested module 'https://cdn.pika.dev/computed-types' does not provide an export named 'array'

### ISSUE THREAD

**Issue by SirJosh3917** [neuledge/computed-types#34]
**Problem:** The suggested deno import using pika CDN fails. This might be something to do with the mixing of newer and older ES* imports, or the fact that the typescript definitions are provided separately, or something in the middle - either way, it doesn't work.

**Solution:** Use [denoporter](https://github.com/SirJosh3917/denoporter/). I have confirmed it to be working with the provided example, *and* intellisense works with my deno extension.

```ts
import Schema, { Type, string, number, array } from 'https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types/src/index.ts';

const UserSchema = Schema({
  name: string.trim().normalize().between(3, 40).optional(),
  username: /^[a-z0-9]{3,10}$/,
  status: Schema.either('active' as const, 'suspended' as const),
  items: array
    .of({
      id: string,
      amount: number.gte(1).integer(),
    })
    .min(1),
 });
 
 type User = Type<typeof UserSchema>;
 const validator = UserSchema.destruct();
 
 const [err, user] = validator({
   username: 'john1',
   // 🚨 TypeScript Error: Type '"unregistered"' is not assignable to type '"active" | "suspended"'.
   status: 'unregistered',
   items: [{ id: 'item-1', amount: 20 }],
 });
 ```

**Comment by moshest** [comment]
Thank you. I try to play with it with Pika as well with jspm.io but something is going wrong there.. I merge you solution for now.
