### ISSUE TITLE
Transform and validate schema

### ISSUE THREAD

**Issue by calummoore** [neuledge/computed-types#52]
I couldn't find a way to transform the input value and then apply schema validation. My use case is to parse some JSON and then validate it against a schema. Not sure if this is currently possible - I tried a couple of different ways with `transform` and `construct`, but couldn't get it to work.

```tsx
const SchemaB = Schema({
  a: number,
})

const SchemaA = Schema({
  json: string.transform((str) => JSON.parse(str)), // validate this is SchemaB
})
```

Maybe we could add the output type as the second parameter of the transform fn? That way, we can continue to use chaining based on the new transformed type.

```tsx
const SchemaA = Schema({
  json: string.transform((str) => JSON.parse(str), SchemaB).optional(), 
})
```

**Comment by moshest** [comment]
Try:

```ts
const SchemaB = Schema({
  a: number,
});

const SchemaA = Schema({
  json: string.transform((str) => SchemaB(JSON.parse(str))).optional(),
});
```

**Comment by calummoore** [comment]
That works great! Thanks for that. 👍

Maybe it would be useful to add that to the examples in the README?

**Comment by moshest** [comment]
I thought the [Creating new Types](https://github.com/neuledge/computed-types#creating-new-types) section will explain that. Can you push a PR with some changes to clarify it?
