### ISSUE TITLE
Add date type

### ISSUE THREAD

**Issue by calummoore** [neuledge/computed-types#60]
Could we add a built-in date type? Or maybe this would be better as a separate library (e.g. `computed-types-date`). Either way, I think having a way to validate dates is very useful.

**Comment by moshest** [comment]
Yeh, I think it should be on the main package as it one of the native types. It will be something simple like getting an ISO string or a timestamp and convert it to a date.

**Comment by moshest** [comment]
Will do in next few days.

**Comment by moshest** [comment]
Released at v1.3
