### ISSUE TITLE
SchemaInput makes shared union type optional

### ISSUE THREAD

**Issue by SirJosh3917** [neuledge/computed-types#69]
I'm using computed-types 1.3.0. My use case is defining a schema where users can enter one or many of the following, and as per the suggestion in #51, upon using `SchemaInput` it marks the `id` properties as optional despite them being required. Is there any workaround for this?

```ts
import Schema, { SchemaInput, string } from "computed-types";

const A = Schema.either({ id: 1 as const }, { id: 2 as const, data: string.optional() });
type AType = SchemaInput<typeof A>;
```

![image](https://user-images.githubusercontent.com/9854865/95327581-401f0200-0872-11eb-9c52-d015f8fe7879.png)

**Comment by moshest** [comment]
I just added a test for this use case. Looks like the types are current..

**Comment by SirJosh3917** [comment]
After having delved deeper, it seems that this problem is due to the different interpretation of `undefined extends T` in `.d.ts` files versus `.ts` files, a.k.a, a TypeScript bug. I've filed it [here](https://github.com/microsoft/TypeScript/issues/40982).

Upon building the project, and emulating the result of Schema.either in the built `Schema.d.ts` file, this is what I get:

```ts
type A = { id: 1 };
type B = { id: 2, data?: string | null };
// copy and paste Schema.either type
type C = SchemaParameters<ValidatorProxy<Validator<FunctionType<SchemaReturnType<A> | SchemaReturnType<B>, MergeSchemaParameters<SchemaParameters<A> | SchemaParameters<B>>>>>>;
```
![image](https://user-images.githubusercontent.com/9854865/95361986-71f88e80-089b-11eb-8c5d-317c6f44bde9.png)

However, after attempting the same thing in the `Schema.ts` file in the source, I end up with this instead:

![image](https://user-images.githubusercontent.com/9854865/95361928-5c836480-089b-11eb-8040-5c11385c6446.png)

I've narrowed it down to the `SchemaParameters<S>` type behaving differently in the emitted `Schema.d.ts` file and differently in the regular `Schema.ts` file. I then, using `{ id: 1 }` as the type for S, narrowed it down to `[undefined] extends [1]` behaving differently when in `Schema.ts` versus when in `Schema.d.ts`, due to it being a typescript definition file.

**Comment by SirJosh3917** [comment]
Update: after having talked about it with a few other people, it seems that the `.d.ts` files that are being published to NPM aren't being interpreted with strict null checks due to a lack of a tsconfig.json file - i.e., `undefined extends 1` will basically interpreted as `undefined extends 1 | undefined | null` without strict null checks. This is fixable if a `tsconfig.json` file is included in the publish to npm with strict null checks enabled. I'd submit a PR, but I don't know if you'd rather remove the `tsconfig.json` from the `.npmignore` or would rather create a new `tsconfig.json` dedicated to only having `strict` enabled.

**Comment by moshest** [comment]
Is there any problem releasing the `tsconfig.json` as is?

We can just add it to the "files" section on the `package.json` file but I would like you to verify first that having this file there (one level above the `lib` folder) is actually solve the problem.

**Comment by SirJosh3917** [comment]
Closing this because while testing if the fix would work, it started working as expected whenever I tried to get it to break...

I'll re-open this if this happens again, but hey - if it starts working randomly, I'll take it.

**Comment by moshest** [comment]
Awesome! Thanks for the update.
