### ISSUE TITLE
Use existing TypeScript interface as a validator

### ISSUE THREAD

**Issue by AsafKaravani** [neuledge/computed-types#7]
Hi, can I use this library to validate a json at runtime with an existing TypeScript interface?

**Comment by moshest** [comment]
Sure. Once the data validated it will get the inferred type from the `Type` helper, this type should match your interfaces and you can assign it to your type without any hard convention:

```ts
interface Item {
  name: string;
  price: number;
}

const ItemSchema = Schema({
  name: unknown.string().trim(),
  price: unknown.number().float().min(0), 
});

const myItem: Item = ItemSchema(jsonInput);
```

**Comment by AsafKaravani** [comment]
My Interface has hundreds of fields.
Is it not possible to do the following:
`
interface InterfaceWith100Fields {
  name: string; // 1
  price: number; // 2
  ...
  age: string; // 99
  eyes: string; // 100
}

const myObj: InterfaceWith100Fields = Validate(InterfaceWith100Fields, jsonInput);
`

**Comment by moshest** [comment]
So you want to validate only portion of the fields but use TypeScript type for the others?

**Comment by moshest** [comment]
Got it. Unfortunately it's not possible right now as TypeScript is exists only on the compile stage, and the validation runs on the runtime level.

If you can share more about your interface structure maybe it will be possible to write a generator script.

**Comment by AsafKaravani** [comment]
Hmm I understand.
Writing a generator is a great idea! (My interface's structure is not complicated, just long.)
Also, I found that repo:
https://github.com/woutervh-/typescript-is

It seems to be a tsc plugin that creates validate functions from TypeScript interfaces on compile for us to use at runtime.

**Comment by moshest** [comment]
hmmm.. cool project!

Although I can see a few problems with this approach. TypeScript don't have concept of emails for example. So in the interface I would just say `email: string` but what I actually want is the email validation.

On the other hand, the generator logic should be really simple as there is not much to change.
For example:

**Input:**
```ts
interface Item {
 foo: string;
 bar: number;
 nested: {
  point: [number, number],
  labels: string[];
};
```

**Output:**
```ts
const ItemSchema = Schema({
 foo: string,
 bar: number,
 nested: {
  point: [number, number],
  labels: array.of(string),
});

type Item = Type<ItemSchema>;
```

**Comment by AsafKaravani** [comment]
Indeed you are right!
I will create a generator (should be simple).

If you want you can vote on that TypeScript suggestion:
Regex-validated string type
https://github.com/Microsoft/TypeScript/issues/6579

**Comment by moshest** [comment]
Awesome! Let me know if you need any help.

**Comment by Willian-Zhang** [comment]
> Indeed you are right! I will create a generator (should be simple).
> 
> If you want you can vote on that TypeScript suggestion: Regex-validated string type [microsoft/TypeScript#6579](https://github.com/microsoft/TypeScript/issues/6579)

Any plans on releasing your tool?
I found Deno community missing out this really important set of tools.
