### ISSUE TITLE
v.1.4.0 seems to be different from the tagged code? `exact` is missing

### ISSUE THREAD

**Issue by phryneas** [neuledge/computed-types#78]
Hey there :)

I just wanted to use `{strict: true}` on a schema, but it seems like the typings for that are missing.
The release tag for 1.4.0 and the shipped types (and probably code?) do not seem to match up.

See this CodeSandbox: https://codesandbox.io/s/lively-https-lr3ec?file=/src/index.ts

**Comment by moshest** [comment]
Thanks. Looks like I had a bug somehow and released outdated versions as 1.4. 

Our latest version is v1.3.2. I just released 1.5.0 as current version to fix this bug.

**Comment by phryneas** [comment]
Thanks :)
