### ISSUE TITLE
`string.optional()` converts empty string to default value

### ISSUE THREAD

**Issue by phryneas** [neuledge/computed-types#94]
I have the situation where I am displaying a very big form that I am not completely initializing with default values and am only setting values once something has actually been touched by the user.

So an optional string value being `undefined` means in my logic "this has not been touched by the user, keep it as is" while an empty string means "the user has set this text field to empty, probably by deleting out a value".

Now, `string.optional()` sets both `undefined` and `""` to `undefined` while `string.optional("")` sets both `undefined` and `""` to `""`, which means I am losing the distinction between these cases.

Can this be considered a bug in `computed-types` or is this intended behaviour? 
Also, it there a good way to get around this? Right now, I am using 
```ts
export function optional<T>(t: T) {
    return Schema.either((val?: undefined) => {
        if (typeof val !== 'undefined') {
            throw new TypeError('is not undefined!');
        }
        return undefined;
    }, t);
}
```
which allows me to use `optional(string)` instead, but it feels pretty "off".

**Comment by moshest** [comment]
This is actually an expected behavior so I added `.strictOptional()` method as well to address that.

Thanks for reporting!

**Comment by phryneas** [comment]
Thank you for the quick solution!
